"""Add updated_at and case_details to Case model

Revision ID: 3ce9f24c3cf0
Revises: 488450c1d120
Create Date: 2025-04-17 11:13:32.800850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce9f24c3cf0'
down_revision = '488450c1d120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('case_details', sa.JSON(), nullable=True))
        batch_op.create_unique_constraint(None, ['case_number'])

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('case_details')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
