"""Add User model and user_id FK to Case

Revision ID: 45ff7d410f4c
Revises: 3ce9f24c3cf0
Create Date: 2025-04-23 13:44:44.488785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ff7d410f4c'
down_revision = '3ce9f24c3cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Use op.f() for index names for consistency, though batch_op.f() also works here
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        # --- MODIFIED LINE ---
        # Added explicit constraint name using op.f() for the foreign key
        batch_op.create_foreign_key(batch_op.f('fk_cases_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        # --- MODIFIED LINE ---
        # Use the same explicit name generated by op.f() for dropping
        batch_op.drop_constraint(batch_op.f('fk_cases_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # Use op.f() for index names for consistency
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###