"""add defendant_counsel_email and defendant_counsel_phone fields

Revision ID: 55d82441cfbb
Revises: 426b15d6654e
Create Date: 2025-05-15 11:57:58.242137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = '55d82441cfbb'
down_revision = '426b15d6654e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('defendant_counsel_email', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('defendant_counsel_phone', sa.String(length=1000), nullable=True))
        batch_op.alter_column('incident_description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('vehicle_details',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # Handle case_details type conversion separately
    op.execute(text('ALTER TABLE "case" ALTER COLUMN case_details TYPE JSON USING case_details::json'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.alter_column('vehicle_details',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('incident_description',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('defendant_counsel_phone')
        batch_op.drop_column('defendant_counsel_email')

    # Handle case_details type conversion separately
    op.execute(text('ALTER TABLE "case" ALTER COLUMN case_details TYPE TEXT USING case_details::text'))

    # ### end Alembic commands ###
