"""add defendants and active_defendant fields to case model

Revision ID: 94f4aa6e8ef4
Revises: 6f1c442f3b06
Create Date: 2025-05-30 11:10:43.710771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f4aa6e8ef4'
down_revision = '6f1c442f3b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('defendants', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('active_defendant', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('active_defendant')
        batch_op.drop_column('defendants')

    # ### end Alembic commands ###
