"""Add jurisdiction and filing_date columns to Case model

Revision ID: cb4c200f0989
Revises: 3a8d856b2685
Create Date: 2025-04-28 15:13:22.777785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4c200f0989'
down_revision = '3a8d856b2685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jurisdiction', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('county', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('filing_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('trial_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('incident_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('incident_location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('incident_description', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('case_type', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('defendant_counsel_info', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('vehicle_details', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('plaintiff_counsel_info', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('plaintiff_counsel_info')
        batch_op.drop_column('vehicle_details')
        batch_op.drop_column('defendant_counsel_info')
        batch_op.drop_column('case_type')
        batch_op.drop_column('incident_description')
        batch_op.drop_column('incident_location')
        batch_op.drop_column('incident_date')
        batch_op.drop_column('trial_date')
        batch_op.drop_column('filing_date')
        batch_op.drop_column('county')
        batch_op.drop_column('jurisdiction')

    # ### end Alembic commands ###
