"""add caption text block fields to case model

Revision ID: f90f33a6c4b3
Revises: 94f4aa6e8ef4
Create Date: 2025-06-18 10:07:18.147705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f90f33a6c4b3'
down_revision = '94f4aa6e8ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caption_top_right', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('caption_top_left', sa.Text(), nullable=True))
        batch_op.alter_column('acting_attorney',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.alter_column('acting_attorney',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.drop_column('caption_top_left')
        batch_op.drop_column('caption_top_right')

    # ### end Alembic commands ###
