"""Initial database schema

Revision ID: 488450c1d120
Revises: 
Create Date: 2025-04-16 14:03:56.383337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488450c1d120'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('official_case_name', sa.String(length=200), nullable=True),
    sa.Column('case_number', sa.String(length=100), nullable=True),
    sa.Column('judge', sa.String(length=150), nullable=True),
    sa.Column('plaintiff', sa.String(length=200), nullable=True),
    sa.Column('defendant', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name'),
    sa.UniqueConstraint('official_case_name')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('analysis_json', sa.JSON(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    op.drop_table('case')
    # ### end Alembic commands ###
